### ISSUE TITLE
Can't upgrade Testlink from 1.9.19 to 1.9.20 (docker)

### ISSUE THREAD

**Issue by r2r200** [bitnami/bitnami-docker-testlink#112]
**Description**
Hello!
I had testilnk 1.9.16 with mariadb in docker which was successfully upgraded to 1.9.19. But now I have no success in upgrading it from 1.9.19 to 1.9.20 - after upgrade testlink can't connect to database. Though the same docker-compose.yml file works correctly with clean DB. SQL script (https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/install/sql/alter_tables/1.9.20/mysql/DB.1.9.20/step1/db_schema_update.sql) for updating DB schema can't be applied due to error.
Is this migration possible? Could you suggest a solution, please?

New docker-compose fie:
```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=*****
      - MARIADB_USER=*****
      - MARIADB_PASSWORD=*****
      - MARIADB_DATABASE=bitnami_testlink
    volumes:
      - './mysql_db:/bitnami/mariadb'
  testlink:
    image: 'bitnami/testlink:1.9.20-debian-10-r301'
    labels:
      kompose.service.type: nodeport
    environment:
#      - TESTLINK_USERNAME=*******
#      - TESTLINK_PASSWORD=******
      - TESTLINK_EMAIL=*****
      - TESTLINK_DATABASE_USER=*****
      - TESTLINK_DATABASE_PASSWORD=*****
      - TESTLINK_SMTP_ENABLE=true
      - TESTLINK_SMTP_HOST=*****
      - TESTLINK_SMTP_PORT=*****
      - TESTLINK_SMTP_USER=*****
      - TESTLINK_SMTP_PASSWORD=*****
      - TESTLINK_SMTP_PROTOCOL=tls
    user: root
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
#      - './testlink_data:/bitnami'
    depends_on:
      - mariadb
```
**Steps to reproduce the issue:**
1. Edited docker-compose file into a view listed above
2. Executed `docker-compose up -d --build`

**Describe the results you received:**
Got error in `docker-compose logs -f`:
```
testlink_1  | testlink 11:21:19.76 INFO  ==> Trying to connect to the database server
testlink20upgr_testlink_1 exited with code 1
```
