### ISSUE TITLE
Filter for execute tests fails - testlink:1.9.20-debian-10

### ISSUE THREAD

**Issue by r2r200** [bitnami/bitnami-docker-testlink#113]
**Description**
Hello!
I have testlink:1.9.20-debian-10-r343 with mariadb in docker which was successfully upgraded from 1.9.19 (and earlier from 1.9.16).
Filter for execute tests doesn't work for me. When I choose Execution type "Manual" and click "Apply" I get errors instead of left iframe. I had also tried r345 version but got the same result.

Could you help me, please?

**Steps to reproduce the issue:**

1. Open Execute tests
2. Choose Execution type "Manual" (it also works for me if I select low, medium or high priority)
3. Push the button "Apply"

**Describe the results you received:**

```
DB Access Error - debug_print_backtrace() OUTPUT START 
 ATTENTION: Enabling more debug info will produce path disclosure weakness (CWE-200) 
            Having this additional Information could be useful for reporting 
            issue to development TEAM. 
 ============================================================================== 
#0  database->exec_query() called at [/opt/bitnami/testlink/lib/functions/database.class.php:641]
#1  database->fetchRowsIntoMap() called at [/opt/bitnami/testlink/lib/functions/execTreeMenu.inc.php:191]
#2  execTree() called at [/opt/bitnami/testlink/lib/functions/tlTestCaseFilterControl.class.php:1079]
#3  tlTestCaseFilterControl->build_tree_menu() called at [/opt/bitnami/testlink/lib/execute/execNavigator.php:35]
```

**Describe the results you expected:**

Expected result is a filtered list of tests

**Version**

- Output of `docker version`:

```
version: '2'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=*********
      - MARIADB_USER=*********
      - MARIADB_PASSWORD=*********
      - MARIADB_DATABASE=*********
    volumes:
      - './mysql_db:/bitnami'
  testlink:
    image: 'bitnami/testlink:1.9.20-debian-10-r343'
    labels:
      kompose.service.type: nodeport
    environment:
      - TESTLINK_USERNAME=*********
      - TESTLINK_PASSWORD=*********
      - TESTLINK_EMAIL=*********
#      - MARIADB_PASSWORD=*********
      - TESTLINK_DATABASE_PASSWORD=*********
      - TESTLINK_SMTP_ENABLE=true
      - TESTLINK_SMTP_HOST=*********
      - TESTLINK_SMTP_PORT=*********
      - TESTLINK_SMTP_USER=*********
      - TESTLINK_SMTP_PASSWORD=*********
      - TESTLINK_SMTP_PROTOCOL=tls
#    user: root
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
#      - './apache_data:/bitnami/apache'
      - './testlink_data:/bitnami/testlink'
      - './templates_plan:/opt/bitnami/testlink/gui/templates/plan'
      - './testlink_logs:/opt/bitnami/testlink/logs'
    depends_on:
      - mariadb
```
