### ISSUE TITLE
Username and password does not working

### ISSUE THREAD

**Issue by charlescit** [bitnami/bitnami-docker-testlink#33]
I'm trying use the application after docker up, but the user name and password it is wrong
I tried:
admin/admin
admin/verysecretadminpassword

and I tried to pass the environment in docker-compose.yml, but does not work too.
- TESTLINK_USERNAME=my_user
 TESTLINK_PASSWORD=my_password

Can You help me?

**Comment by carrodher** [comment]
Hi @charlescit, I am trying to reproduce your issue, but on my machine, it works without problem.

- If you run `$ docker-compose up` (with the default `docker-compose.yml`), the user is `user` and the password is `bitnami`.

- If you run `$ docker-compose up` with a `docker-compose.yml` like the following:
```yaml
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  testlink:
    image: 'bitnami/testlink:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'testlink_data:/bitnami/testlink'
      - 'apache_data:/bitnami/apache'
    depends_on:
      - mariadb
    environment:
      TESTLINK_USERNAME: my_user
      TESTLINK_PASSWORD: my_password

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
  apache_data:
    driver: local
```
you should be able to login with user `my_user` and password `my_password`.

I hope this information is useful for you. If you have any other question, please do not hesitate to let us know.

Best Regards,
Carlos R. Hernández
