### ISSUE TITLE
No option to specify connection to ldap

### ISSUE THREAD

**Issue by xeagle2** [bitnami/bitnami-docker-testlink#61]
There is a lack of the feature to establish connection to ldap as auth source for the application.

**Comment by juan131** [comment]
Hi @xeagle2 


Could you please explain a little more what's your suggestion? Would you like to be able to add extra-configuration to TestLink via Environment Variables as we do wit `TESTLINK_LANGUAGE` or `TESTLINK_EMAIL`?

https://github.com/bitnami/bitnami-docker-testlink#environment-variables

**Comment by xeagle2** [comment]
Hi @juan131 

My initial intention was to configure testlink to use ldap authentication method by default instead of DB and this type of authentication requires to configure more around 5-7 additional ldap related properties.

Your suggestion to use Environment Variables would work, however I think it would over complicate the number of supported configuration parameters. 

If we don't take into account the docker volume, what I mean, is the testlink in general has a huge number of configuration parameters that could be overridden in custom_config.inc.php. It would be probably better to introduce single TESTLINK_CONFIG ENV variable which will be directly written to custom_config.inc.php. 

I hope it would help others also to simplify the configuration of docker image.

**Comment by juan131** [comment]
Hi @xeagle2 

I think that could be really interesting. @jotadrilo @tompizmor do you think we could implement this solution on the Nami logic?

**Comment by jotadrilo** [comment]
Hi @xeagle2 @juan131 

Even though I recall having seen this proposal in other images, I am not really a fan of injecting `ENV` variables containing plain code to a file. Anyway, your proposal is totally feasible.

I have some different point of views that I would like to check with you.

One of them is about having another external configuration file that we can require from `custom_config.inc.php`. Something like:

```
if ( file_exists('./extra-config.inc.php') )
	require ('./extra-config.inc.php');
```

It is so redundant, though. Testlink already loads the `custom-config.inc.php` file to fit this role.

Another is just about mounting your custom `custom-config.inc.php` on top of ours:

```
  testlink:
    image: 'bitnami/testlink:1'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'testlink_data:/bitnami'
      - /path/to/custom-config.inc.php:/bitnami/testlink/conf/custom-config.inc.php:ro
    depends_on:
      - mariadb
```

This would work only if you already have a running deployment so our initialization scripts do not overwrite this file (failing, as it is mounted in read-only mode).

```
docker-compose up
docker-compose down
# Modify the docker-compose here
docker-compose up
```

The latest is a workaround that you could try if you are ok having these intermediate steps.

Waiting for your feedback!
I hope it helps.
