### ISSUE TITLE
username/password in compose yml does not work

### ISSUE THREAD

**Issue by cyberyoung** [bitnami/bitnami-docker-testlink#79]
**Description**

**Steps to reproduce the issue:**

use docker-compose.yml like following
```
version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
  testlink:
    image: 'bitnami/testlink:latest'
    ports:
      - '8083:80'
      - '7443:443'
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      TESTLINK_USERNAME: my_user
      TESTLINK_PASSWORD: my_password

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
```

**Describe the results you received:**
my_user/my_password
wrong username / password

user/bitnami
login successfully

**Describe the results you expected:**
username/password config allow me use custom admin account.
I found #33 but nothing can help me.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 21
 Running: 18
 Paused: 0
 Stopped: 3
Images: 48
Server Version: 18.06.1-ce
Storage Driver: devicemapper
 Pool Name: docker-8:1-114032652-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: xxxx
 Metadata loop file: xxxxx
 Data Space Used: 17.26GB
 Data Space Total: 107.4GB
 Data Space Available: 90.11GB
 Metadata Space Used: 24.21MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.123GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.146-RHEL7 (2018-01-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.63GiB
Name: dev-machine
ID: KBSA:SZ5J:534G:JTTN:X4SD:JS66:UI77:V4HN:CHHC:AKD5:6CDE:ZDTH
Docker Root Dir: xxxxxxx
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 3.4.9
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by cyberyoung** [comment]
And seems SMTP cannot work either

**Comment by Lakshmipathi** [comment]
I'm also facing running into SMTP issue. Any pointers on  which testlink files under /opt/bitnami will be affected/updated if we provide SMTP env values. I hope to edit those php files manually and check.

**Comment by Lakshmipathi** [comment]
@cyberyoung , Possible workaround: If you want you can add new/desired username from TestLink web-ui (User management) and provide appropriate roles

**Comment by juan131** [comment]
Hi @cyberyoung 

I was unable to reproduce the issue using the **docker-compose.yaml** below:

```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  testlink:
    image: 'bitnami/testlink:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - TESTLINK_USERNAME=my_user
      - TESTLINK_PASSWORD=my_password
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
```

Please note that I set the environment using the format:

```
 - ENV_VAR=value
```

Instead of:

```
 ENV_VAR: value
```

I'll update the README.md file since there are some contradictory instructions about the format to use.
