### ISSUE TITLE
custom_config.inc.php not getting updated with provided SMTP values and missing ctlscript.sh 

### ISSUE THREAD

**Issue by Lakshmipathi** [bitnami/bitnami-docker-testlink#80]
Running  latest testlink docker-compose file produces two issues. 

SMTP Issue: 

Even after exporting SMTP env as suggested here https://github.com/bitnami/bitnami-docker-testlink/issues/49#issuecomment-343933443
The file `/opt/bitnami/testlink/custom_config.inc.php` appears with 

```
 cat custom_config.inc.php
<?php

$tlCfg->log_path = '/opt/bitnami/testlink/logs/';
$g_repositoryPath = '/opt/bitnami/testlink/upload_area/';
$tlCfg->config_check_warning_mode = 'SCREEN';
$g_smtp_host = '';
$g_tl_admin_email = 'user@example.com';
$g_from_email = 'user@example.com';
$g_return_path_email = 'user@example.com';
$g_smtp_username = '';
$g_smtp_password = '';
$g_smtp_port = '';
$g_smtp_connection_mode = '';

$tlCfg->default_language = 'en_US';

?>
```

Issue 2: 

**ctlscript.sh** missing under /opt/bitnami

Here is the content of docker-compose file
```

$cat docker-compose.yml 

version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  testlink:
    image: 'bitnami/testlink:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - SMTP_ENABLE=true
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=my_user@gmail.com
      - SMTP_PASSWORD=my_password
      - SMTP_CONNECTION_MODE=tls

    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local

```

**Comment by andresbono** [comment]
Hi @Lakshmipathi,

**SMTP Issue:**
Was it the first run of the container?

**Issue 2**
Why would you expect to have a `ctlscript.sh`? Did you use the [Bitnami Testlink Stack](https://bitnami.com/stack/testlink) before? Please note that our containers use a different technology to configure and install applications and it doesn't use the `ctlscript.sh`.

**Comment by Lakshmipathi** [comment]
@andresbono 

Thanks for the response. 

**SMTP  Issue:**
Yes, But the file didn't updated even after `docker-compose stop` followed by `start` again. 

**Issue 2**
Oops sorry. Yes earlier I was using Bitnami TestLink Stack. While I was searching on SMTP some solution referred to restarting services with `ctlscript.sh`. So got confused Bitnami TestLink Stack with Bitnami Test Container! thanks for clarification.

**Comment by carrodher** [comment]
Hi @Lakshmipathi, the SMTP environment variables take effect in the initialization of the application only, so you need to remove the persistent volume associated to the application. Please, note that you will loose all the application data by doing it. Then, you can reinitialize the application and the SMTP environment variables will be applied.
```bash
docker-compose down --volumes
docker-compose up
```
The `stop`/`start` is not an option in this case, because it is not doing an application initialization.

I just used your `docker-compose.yaml`:
```yaml
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  testlink:
    image: 'bitnami/testlink:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - SMTP_ENABLE=true
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=my_user@gmail.com
      - SMTP_PASSWORD=my_password
      - SMTP_CONNECTION_MODE=tls

    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
```

And the SMTP variables are applied properly by running `docker-compose up`:
```bash
$ cat /opt/bitnami/testlink/custom_config.inc.php
```
```php
<?php

$tlCfg->log_path = '/opt/bitnami/testlink/logs/';
$g_repositoryPath = '/opt/bitnami/testlink/upload_area/';
$tlCfg->config_check_warning_mode = 'SCREEN';
$g_smtp_host = 'smtp.gmail.com';
$g_tl_admin_email = 'user@example.com';
$g_from_email = 'user@example.com';
$g_return_path_email = 'user@example.com';
$g_smtp_username = 'my_user@gmail.com';
$g_smtp_password = 'my_password';
$g_smtp_port = '587';
$g_smtp_connection_mode = 'tls';

$tlCfg->default_language = 'en_US';

?>
```
