### ISSUE TITLE
when I change the case ExecutionType, the server returns me 500 Internal Server Error

### ISSUE THREAD

**Issue by sumoning** [bitnami/bitnami-docker-testlink#97]
**Description**

**Steps to reproduce the issue:**

1. create project\suite\testcases .etc
2. using TestLink-API-Python-client-0.8.1 to change the testcase ExecutionType, from MANUAL to AUTOMATED
3. use two python method
```python
for plan in tlc.getProjectTestPlans(tlc.getTestProjectByName('ParaStor').get('id')):
    for suit in tlc.getTestSuitesForTestPlan(plan.get('id')):
        for case in tlc.getTestCasesForTestSuite(suit.get('id'), True, 'simple'):
            print tlc.updateTestCase(tlc.getTestCase(case.get('id'))[0].get('tc_external_id'), executiontype=2)
```
```python
for plan in tlc.getProjectTestPlans(tlc.getTestProjectByName('ParaStor').get('id')):
    for suit in tlc.getTestSuitesForTestPlan(plan.get('id')):
        for case in tlc.getTestCasesForTestSuite(suit.get('id'), True, 'simple'):
            #print tlc.updateTestCase(tlc.getTestCase(case.get('id'))[0].get('tc_external_id'), executiontype=2)
            print tlc.setTestCaseExecutionType(testcaseexternalid=tlc.getTestCase(case.get('id'))[0].get('tc_external_id'),version=1, testprojectid=tlc.getTestProjectByName('ParaStor').get('id'), executiontype=2)
```

**Describe the results you received:**

it return me 500 internal server error
```
ssh://ubuntu@10.2.48.152:22/usr/bin/python -u /tmp/pycharm_project_446/testtestlink.py
Traceback (most recent call last):
  File "/tmp/pycharm_project_446/testtestlink.py", line 47, in <module>
    version=1, testprojectid=tlc.getTestProjectByName('ParaStor').get('id'), executiontype=2)
  File "/tmp/pycharm_project_446/testlink/testlinkdecorators.py", line 112, in wrapperAddDevKey
    return methodAPI(self, *argsPositional, **argsOptional)
  File "/tmp/pycharm_project_446/testlink/testlinkdecorators.py", line 100, in wrapperWithArgs
    *argsPositional, **argsOptional)
  File "/tmp/pycharm_project_446/testlink/testlinkapigeneric.py", line 1582, in callServerWithPosArgs
    response = self._callServer(methodNameAPI, argsOptional)
  File "/tmp/pycharm_project_446/testlink/testlinkapigeneric.py", line 2061, in _callServer
    raise testlinkerrors.TLConnectionError(new_msg)
testlink.testlinkerrors.TLConnectionError: problems connecting the TestLink Server http://10.2.48.153/lib/api/xmlrpc/v1/xmlrpc.php
<ProtocolError for 10.2.48.153/lib/api/xmlrpc/v1/xmlrpc.php: 500 Internal Server Error>

Process finished with exit code 1
```

**Describe the results you expected:**

I think it can change the testcase ExecutionType from MANUAL to AUTOMATED

**Additional information you deem important (e.g. issue happens only occasionally):**
the php log as follows
```
testlink    | [Tue Apr 14 11:42:30.036067 2020] [php7:error] [pid 112] [client 10.2.48.152:35158] PHP Fatal error:  Uncaught Exception: testcase::getInternalID EXCEPTION: When using just numeric part of External ID, test project ID, is mandatory in /opt/bitnami/testlink/lib/functions/testcase.class.php:3111\nStack trace:\n#0 /opt/bitnami/testlink/lib/api/xmlrpc/v1/xmlrpc.class.php(2535): testcase->getInternalID('1')\n#1 /opt/bitnami/testlink/lib/api/xmlrpc/v1/xmlrpc.class.php(1120): TestlinkXMLRPCServer->checkTestCaseIdentity('(setTestCaseExe...')\n#2 /opt/bitnami/testlink/lib/api/xmlrpc/v1/xmlrpc.class.php(5978): TestlinkXMLRPCServer->_runChecks(Array, '(setTestCaseExe...')\n#3 /opt/bitnami/testlink/third_party/xml-rpc/class-IXR.php(350): TestlinkXMLRPCServer->setTestCaseExecutionType(Array)\n#4 /opt/bitnami/testlink/third_party/xml-rpc/class-IXR.php(302): IXR_Server->call('tl.setTestCaseE...', Array)\n#5 /opt/bitnami/testlink/third_party/xml-rpc/class-IXR.php(285): IXR_Server->serve('<?xml version='...')\n#6 /opt/bitnami/testlink/lib/api/xmlrpc/v1/xmlrpc.class.php(273): IXR_Server->__construct(Array)\n#7 /opt/bitnami/testlink/lib in /opt/bitnami/testlink/lib/functions/testcase.class.php on line 3111

```

**Version**

- Output of `docker version`:

```
[root@vm48153 ~ 11:55:04]# docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:33:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:02:24 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
[root@vm48153 ~ 11:55:06]# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.11.6.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.638GiB
Name: vm48153
ID: 44IG:Y46K:25G4:AEDA:JZXO:MMYE:EFKI:NUUZ:RBLH:K55O:HKCQ:LBR7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://7oqe47st.mirror.aliyuncs.com/
Live Restore Enabled: false
Product License: Community Engin
```

- Output of `docker-compose version` (if applicable):

```
[root@vm48153 ~ 11:55:27]# docker-compose version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Vmware ESXI 6.7

**Comment by sumoning** [comment]
my docker_compose.yml
```yaml
version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    container_name: mariadb
    hostname: mariadb
    environment:
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - TZ=Asia/Shanghai
    volumes:
      - 'mariadb_data:/bitnami'
    networks:
      - bridge
  testlink:
    image: 'bitnami/testlink:1.9.20'
    container_name: testlink
    hostname: testlink
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - TZ=Asia/Shanghai
    ports:
      - '80:80'
      - '443:443'
    volumes:
      #- ./sources.list:/etc/apt/sources.list:ro
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb
    networks:
      - bridge

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
networks:
  bridge:
    driver: bridge
```
