### ISSUE TITLE
APACHE_ENABLE_CUSTOM_PORTS

### ISSUE THREAD

**Issue by LetMyPplGo** [bitnami/bitnami-docker-testlink#98]
Kind of a bug in documentation.
The section about custom ports for Apache is missing APACHE_ENABLE_CUSTOM_PORTS=yes.
It seems that without this environment variable Apache doesn't pick up the custon ports.

**Comment by marcosbc** [comment]
Hi @LetMyPplGo, thanks for reporting but the docs are correct. That environment variable is set automatically during the initialization, which is called in the app-entrypoint: https://github.com/bitnami/bitnami-docker-testlink/blob/master/1/debian-10/rootfs/apache-init.sh#L4

I tried setting `APACHE_HTTP_PORT_NUMBER=8081` and it worked without issues, the HTTP port was changed to 8081.

**Comment by LetMyPplGo** [comment]
Hi Marcos!
Strangely that didn't work for me.
Setting just
      - APACHE_HTTP_PORT_NUMBER=8088
      - APACHE_HTTPS_PORT_NUMBER=8443
...did not redirect Apache ports. 
Env variable APACHE_ENABLE_CUSTOM_PORTS was set to 'no' in the container and as a result httpd.conf contained 'Listen 80'.
When I explicitly specified it in the docker-compose.yml, everything started working as expected.

**Comment by marcosbc** [comment]
@LetMyPplGo Could you share your `docker-compose.yml`? With the one below it works without issues for us:

```yaml
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  testlink:
    image: 'bitnami/testlink:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - APACHE_HTTP_PORT_NUMBER=8081
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
```

NOTE: If you override the entrypoint, then you would need to do what you mention. See `/app-entrypoint.sh` and `/apache-init.sh` in the container for more information.

**Comment by LetMyPplGo** [comment]
I performed an experiment: removed the line "- APACHE_ENABLE_CUSTOM_PORTS=yes" from the docker-compose.yml. The result: "Listen 80" in the httpd.conf.

Here is my config:
```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  testlink:
    image: 'bitnami/testlink:1'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - APACHE_ENABLE_CUSTOM_PORTS=yes
      - APACHE_HTTP_PORT_NUMBER=8088
      - APACHE_HTTPS_PORT_NUMBER=8443
    ports:
      - '8088:8088'
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local

```
